// Generated by CoffeeScript 1.4.0
(function() {

  (function(win, doc, exports) {
    var append, num, target, text,
      _this = this;
    target = $("#wrap");
    text = "";
    num = 0;
    append = function() {
      if (num % 30 === 0) {
        target.append(text);
        text = "";
      }
      if (num < 170000) {
        setTimeout(append, 0);
      } else {
        alert("finish!!");
      }
      text += "<p>&#" + num + "</p>";
      return num += 1;
    };
    return append();
  })(window, document, window);

}).call(this);
